from __future__ import annotations

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / ".github" / "scripts" / "audit_markdown.py"
SPEC = importlib.util.spec_from_file_location("audit_markdown", SCRIPT)
assert SPEC and SPEC.loader
audit = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = audit
SPEC.loader.exec_module(audit)


class MarkdownAuditTests(unittest.TestCase):
    def homepage_policy(self, components: list[str], quick_links: list[str]) -> dict:
        return {
            "english": "README.md",
            "chinese": "README_ZH.md",
            "profile": "multi-product-hub",
            "required_components": components,
            "required_quick_links": quick_links,
            "required_badges": [],
            "required_h2_icons": [],
            "h3_emoji_allow_patterns": [],
        }

    def test_name_status_parser_keeps_rename_and_deleted_paths(self) -> None:
        paths = audit.parse_name_status_z(
            "R100\0docs/old.md\0docs/new.md\0D\0docs/deleted.md\0"
        )
        self.assertEqual(
            ["docs/deleted.md", "docs/new.md", "docs/old.md"],
            paths,
        )

    def test_bilingual_companion_names(self) -> None:
        self.assertEqual("docs/CI_ZH.md", audit.expected_companion("docs/CI.md"))
        self.assertEqual("docs/CI.md", audit.expected_companion("docs/CI_ZH.md"))

    def test_public_text_hygiene_detects_local_paths_ports_and_tokens(self) -> None:
        findings = audit.check_public_text(
            "README.md",
            "C:\\Users\\name COM36 ghp_12345678901234567890",
        )
        self.assertEqual(
            {"LOCAL_ABSOLUTE_PATH", "ACTUAL_SERIAL_PORT", "CREDENTIAL_OR_TOKEN"},
            {finding.code for finding in findings},
        )

    def test_public_text_hygiene_detects_tool_provenance_without_product_phrase_false_positive(self) -> None:
        provenance_samples = (
            "This page was generated by OpenAI.",
            "This page was generated with ChatGPT.",
            "This page was authored by Codex.",
            "This page was written using GPT-5.3.",
            "This page was created by Claude.",
            "This page was reviewed with Gemini.",
            "This page was assisted by Copilot.",
            "This page was edited with Cursor.",
        )
        product = audit.check_public_text("README.md", "This product model supports AI applications.")
        for sample in provenance_samples:
            with self.subTest(sample=sample):
                provenance = audit.check_public_text("README.md", sample)
                self.assertEqual(["TOOL_OR_MODEL_PROVENANCE"], [finding.code for finding in provenance])
        self.assertEqual([], product)

    def test_homepage_policy_rejects_missing_hero_image(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            (root / "README.md").write_text(
                '<div align="center">\n<h1>Family</h1>\n<p><a href="README_ZH.md">中文</a> <a href="https://www.waveshare.com/product.htm">🌐 Product</a></p>\n</div>\n\n---\n\n## ✨ Overview',
                encoding="utf-8",
            )
            (root / "README_ZH.md").write_text(
                '<div align="center">\n<h1>系列</h1>\n<p><a href="README.md">English</a> <a href="https://www.waveshare.net/shop/product.htm">🌐 产品系列</a></p>\n</div>\n\n---\n\n## ✨ 概述',
                encoding="utf-8",
            )
            config = audit.load_config(None)
            config["homepage_pairs"] = [self.homepage_policy(["hero_image"], ["product"])]
            findings = audit.check_homepage(root, config)
        self.assertEqual(2, sum(finding.code == "HOMEPAGE_COMPONENT_MISSING" for finding in findings))

    def test_homepage_policy_rejects_missing_product_quick_link(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            for name, language in (("README.md", "README_ZH.md"), ("README_ZH.md", "README.md")):
                (root / name).write_text(
                    f'<div align="center">\n<h1>Family</h1>\n<p><a href="{language}">Language</a> <a href="https://docs.waveshare.com/family">📚 Documentation</a></p>\n<img src="assets/hero.jpg" alt="Family hero">\n</div>\n\n---\n\n## ✨ Overview',
                    encoding="utf-8",
                )
            config = audit.load_config(None)
            config["homepage_pairs"] = [self.homepage_policy(["quick_links"], ["product"])]
            findings = audit.check_homepage(root, config)
        self.assertEqual(2, sum(finding.code == "HOMEPAGE_QUICK_LINK_MISSING" for finding in findings))

    def test_repository_homepage_policy_passes(self) -> None:
        config = audit.load_config(ROOT / ".github" / "scripts" / "markdown-audit-config.json")
        self.assertEqual([], audit.check_homepage(ROOT, config))


    def test_local_link_check_distinguishes_present_and_missing_targets(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            (root / "docs").mkdir()
            (root / "docs" / "present.md").write_text("ok", encoding="utf-8")
            findings = audit.check_links(
                root,
                "README.md",
                "[present](docs/present.md) [missing](docs/missing.md)",
            )
        self.assertEqual(["RELATIVE_LINK_MISSING"], [finding.code for finding in findings])

    def test_docs_only_scope_rejects_source_files(self) -> None:
        config = audit.load_config(None)
        findings = audit.docs_only_findings(
            ROOT,
            ["docs/CI.md", "examples/esp-idf/02_HelloWorld/main/main.c"],
            config,
        )
        self.assertEqual(["DOCS_ONLY_SCOPE"], [finding.code for finding in findings])

    def test_deleting_one_language_page_reports_orphaned_companion(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            (root / "GUIDE_ZH.md").write_text("[English](GUIDE.md)", encoding="utf-8")
            findings = audit.deleted_pair_findings(
                root,
                ["GUIDE.md"],
                audit.load_config(None),
            )
        self.assertEqual(
            ["BILINGUAL_PAIR_ORPHANED"],
            [finding.code for finding in findings],
        )

    def test_reciprocal_language_links_require_both_pages_near_the_top(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            (root / "GUIDE.md").write_text("[中文](GUIDE_ZH.md)", encoding="utf-8")
            (root / "GUIDE_ZH.md").write_text("Guide", encoding="utf-8")
            findings = audit.check_reciprocal_language_links(
                root, "GUIDE.md", audit.load_config(None)
            )
        self.assertEqual(
            ["BILINGUAL_NAVIGATION_MISSING"],
            [finding.code for finding in findings],
        )

    def test_wrong_language_internal_links_require_existing_companions(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            for name in ("GUIDE.md", "GUIDE_ZH.md", "OTHER.md", "OTHER_ZH.md"):
                (root / name).write_text("page", encoding="utf-8")
            english = audit.check_wrong_language_links(root, "GUIDE.md", "[other](OTHER_ZH.md)")
            chinese = audit.check_wrong_language_links(root, "GUIDE_ZH.md", "[other](OTHER.md)")
        self.assertEqual(["WRONG_LANGUAGE_INTERNAL_LINK"], [finding.code for finding in english])
        self.assertEqual(["WRONG_LANGUAGE_INTERNAL_LINK"], [finding.code for finding in chinese])

    def test_bilingual_chooser_block_allows_both_language_targets(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            for name in ("GUIDE_ZH.md", "OTHER.md", "OTHER_ZH.md"):
                (root / name).write_text("page", encoding="utf-8")
            findings = audit.check_wrong_language_links(
                root,
                "GUIDE_ZH.md",
                "[English](OTHER.md)\n[中文](OTHER_ZH.md)",
            )
        self.assertEqual([], findings)

    def test_bilingual_links_separated_by_a_blank_line_are_not_one_chooser(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            for name in ("GUIDE_ZH.md", "OTHER.md", "OTHER_ZH.md"):
                (root / name).write_text("page", encoding="utf-8")
            findings = audit.check_wrong_language_links(
                root,
                "GUIDE_ZH.md",
                "[English](OTHER.md)\n\n[中文](OTHER_ZH.md)",
            )
        self.assertEqual(
            ["WRONG_LANGUAGE_INTERNAL_LINK"],
            [finding.code for finding in findings],
        )

    def test_language_link_exemption_suppresses_reciprocal_and_routing_checks(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            (root / "GUIDE.md").write_text("[other](OTHER_ZH.md)", encoding="utf-8")
            (root / "GUIDE_ZH.md").write_text("guide", encoding="utf-8")
            (root / "OTHER.md").write_text("other", encoding="utf-8")
            (root / "OTHER_ZH.md").write_text("其他", encoding="utf-8")
            config = audit.load_config(None)
            config["language_link_exempt_patterns"].append("GUIDE.md")
            reciprocal = audit.check_reciprocal_language_links(root, "GUIDE.md", config)
            routing = audit.check_wrong_language_links(
                root, "GUIDE.md", (root / "GUIDE.md").read_text(encoding="utf-8"), config
            )
        self.assertEqual([], reciprocal)
        self.assertEqual([], routing)


if __name__ == "__main__":
    unittest.main()
